<div id="header-wrapper">
  <div class="5grid-layout">
    <div class="row">
      <div class="12u">

        <header id="header">
          <h1>
            <a href="http://www.placetosee.net/" class="mobileUI-site-name">Place to see</a>
          </h1>
          <nav class="mobileUI-site-nav">
            <a href="http://www.placetosee.net/" class="current-page-item">Home</a>
            <a href="http://www.placetosee.net/Singapore/best-places-in-singapore.html">Singapore</a>
            <a href="http://www.placetosee.net/Dubai/UAE/Dubai/">Dubai</a>
            <a href="http://www.placetosee.net/Indonesia/">Indonesia</a>
            <a href="http://www.placetosee.net/Malaysia/">Malaysia</a>
            <a href="http://www.placetosee.net/Malaysia/">Thailand</a>
            <a href="http://www.placetosee.net/Seychelles/best-places-in-Seychelles.html">Seychelles</a>
        
       
        
           
           
          
            <a href="http://www.placetosee.net/Sitemap.html">Sitemap</a>
          </nav>
        </header>

      </div>
    </div>
  </div>
</div>
