<div id="header-wrapper">
  <div class="5grid-layout">
    <div class="row">
      <div class="12u">

        <header id="header">
          <h1>
            <a href="https://www.kreatewebsites.com/" class="mobileUI-site-name">ATAM</a>
          </h1>
          <nav class="mobileUI-site-nav">
            

   
              <a  href="https://www.kreatewebsites.com/1-Overview.html">Chapter 1</a>
        





              <a href="https://www.kreatewebsites.com/2-Why-to-use-ATAM.html">2</a>
  

              <a  href="https://www.kreatewebsites.com/3-What-does-ATAM-discover.html">3</a>
   





   
              <a href="https://www.kreatewebsites.com/4-ATAM-Cost-and-benefits.html">4</a>
         






              <a  href="https://www.kreatewebsites.com/5-ATAM-Roles.html">5</a>
   



              <a  href="https://www.kreatewebsites.com/6-ATAM-Steps-Summary.html">6</a>
            


              <a  href="https://www.kreatewebsites.com/7-ATAM-Steps.html">7</a>
   


              <a  href="https://www.kreatewebsites.com/8-Tradeoffs.html">8</a>
       




              <a  href="https://www.kreatewebsites.com/9-Sensitivity-Points.html">9</a>
      








            <a href="https://www.kreatewebsites.com/Sitemap.html">Sitemap</a>
          </nav>
        </header>

      </div>
    </div>
  </div>
</div>
